git config --global alias.cim "commit -m"
git config --global alias.st "status -s"
git config --global alias.cob "checkout -b"
git config --global alias.co "checkout"
git config --global alias.last "log -1 HEAD"
git config --global alias.br "branch"
