cinst googlechrome
cinst firefox
cinst nodejs.install
cinst atom
cinst fiddler4
cinst 7zip
cinst wget
cinst curl
cinst dotnetcore
cinst gitkraken
cinst postman
cinst cmder
cinst docker-for-windows
cinst dotnetcore-sdk
cinst ccleaner
cinst sysinternals
cinst microsoft-build-tools
cinst nuget.commandline
